name: ⭐ Track Stars

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: fbuireu/github-star-tracker@79a10863b67173a503e3342df85fde982e4f5906
        with:
          only-repos: 'saucer'
          github-token: ${{ secrets.STAR_TRACKER_TOKEN }}
